### ISSUE TITLE
Failed to load the make-runner-panel package

### ISSUE THREAD

**Issue by vrtxsoft** [mcheung63/make-runner-panel#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: [make-runner-panel](https://github.com/mcheung63/make-runner-panel) package, v0.20.0

### Stack Trace

Failed to load the make-runner-panel package

```
At XRegExp is not a function

TypeError: XRegExp is not a function
    at Object.<anonymous> (/Users/fawadfarooq/.atom/packages/make-runner-panel/lib/make-runner-panel.coffee:8:20)
    at Object.<anonymous> (/Users/fawadfarooq/.atom/packages/make-runner-panel/lib/make-runner-panel.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.0.0
auto-encoding, v0.5.3
auto-id-class, v0.2.6
auto-indent, v0.5.0
auto-require-tags, v0.0.4
auto-run, v0.2.1
auto-semicolon, v1.1.0
autocomplete-love, v0.3.0
autoupdate-packages, v1.3.1
make-runner-panel, v0.20.0
node-debugger, v1.4.6
node-on-fire, v0.1.0
pigments, v0.26.0
project-runner, v0.2.0
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by mcheung63** [comment]
Thanks for submitting bug, i double checked the package config file in the plugin project, i did included xregexp. Can you please check the folder xregexp exist in your mac (please see second attachment)?

<img width="1270" alt="2016-04-02 9 42 29" src="https://cloud.githubusercontent.com/assets/1779905/14223728/4d33cf0e-f8b7-11e5-931f-975f10f94068.png">
<img width="832" alt="2016-04-02 9 44 01" src="https://cloud.githubusercontent.com/assets/1779905/14223733/89680094-f8b7-11e5-9106-bcfa6692160f.png">

**Comment by vrtxsoft** [comment]
yes file  already there but still not working same error again and again

**Comment by mcheung63** [comment]
Thanks Mr Vrtxsoft, let me think and test it. Please give me some time. thanks

**Comment by mcheung63** [comment]
Fixed, thanks Mr Vrtxsoft
